"""empty message

Revision ID: 04d61d0143a9
Revises: 6cff10359490
Create Date: 2021-04-16 10:49:07.495024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d61d0143a9'
down_revision = '6cff10359490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('venues', sa.Column('created_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_date')
    op.drop_column('artists', 'created_date')
    # ### end Alembic commands ###
