"""empty message

Revision ID: 6cff10359490
Revises: a9010e9b2c68
Create Date: 2021-04-14 14:58:39.630355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cff10359490'
down_revision = 'a9010e9b2c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genre_artist_id_fkey', 'artist_genre', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genre', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('venue_genre_venue_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key('venue_genre_venue_id_fkey', 'venue_genre', 'venues', ['venue_id'], ['id'])
    op.drop_constraint(None, 'artist_genre', type_='foreignkey')
    op.create_foreign_key('artist_genre_artist_id_fkey', 'artist_genre', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
